# Tests for data quality
models:
  - name: taxi_silver
    description: "Cleaned NYC Yellow Taxi trips"
    columns:
      - name: trip_distance
        data_tests:
          - not_null
      - name: total_amount # We need to check all the financial columns for errors
        data_tests:
          - not_null
      - name: fare_amount
        data_tests:
          - not_null
      - name: extra
        data_tests:
          - not_null
      - name: tip_amount
        data_tests:
          - not_null
      - name: tolls_amount
        data_tests:
          - not_null
      - name: congestion_surcharge
        data_tests:
          - not_null
      - name: passenger_count
        data_tests:
          - not_null