sources:
  - name: bronze
    schema: bronze
    tables:
      - name: taxi_bronze
        description: "Raw NYC Taxi trips"
        columns:
          - name:  vendor_id
          - name:  tpep_pickup_datetime
          - name:  tpep_dropoff_datetime
          - name:  passenger_count
          - name:  trip_distance
          - name:  RatecodeID
          - name:  store_and_fwd
          - name:  PULocationID
          - name:  DOLocationID
          - name:  payment_type
          - name:  fare_amount
          - name:  extra
          - name:  mta_tax
          - name:  tip_amount
          - name:  tolls_amount
          - name:  total_amount
          - name:  congestion_surcharge